apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "convoy.fullname" . }}
  labels:
    {{- include "convoy.labels" . | nindent 4 }}
data:
  convoy.json: |
    {
        "auth": {
            "is_signup_enabled": false
        }
    }
