apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convoy.fullname" . }}
  labels:
    {{ include "convoy.labels" . | nindent 4 }}
data:
  database-dsn: {{ include "convoy.database.dsn" . | b64enc }}
  redis-dsn: {{ include "convoy.redis.dsn" . | b64enc }}
  smtp-password: {{ .Values.smtp.password | b64enc }}
