apiVersion: v1
kind: Service
metadata:
  name: {{ include "convoy.fullname" . }}
  labels:
    {{- include "convoy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-server
      protocol: TCP
      name: http
  selector:
    {{- include "convoy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/type: server
