{{- if and .Values.persistence.enabled .Values.persistence.filebrowser.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautic.fullname" . }}-filebrowser
  labels:
    {{ include "mautic.labels" . | nindent 4 }}
data:
  admin-filebrowser-password: {{ .Values.persistence.filebrowser.password | b64enc }}
{{- end }}
