apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautic.fullname" . }}
  labels:
    {{ include "mautic.labels" . | nindent 4 }}
data:
  admin-password: {{ .Values.admin.password | b64enc }}
