{{- if and (not .Values.redis.enabled) (not .Values.externalRedis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ printf "%s-%s" (include "mautic.fullname" .) "externalredis" }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
{{- end }}
