apiVersion: v1
kind: Secret
metadata:
  name:  {{ printf "%s-%s" (include "n8n.fullname" .) "smtp" }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  pass: {{ .Values.smtp.pass | b64enc | quote }}
