{{- if and (not .Values.mariadb.enabled) (not .Values.externalDatabase.existingSecret) (not .Values.mariadb.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ printf "%s-%s" (include "n8n.fullname" .) "externaldatabase" }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
