apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "convoy.fullname" . }}
  labels:
    {{- include "convoy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.resources.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "convoy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/type: server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "convoy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/type: server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "convoy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "convoy.fullname" . }}
          configMap:
            name: {{ include "convoy.fullname" . }}
            items:
            - key: convoy.json
              path: convoy.json
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/start.sh" ]
          volumeMounts:
          - name: {{ include "convoy.fullname" . }}
            mountPath: /convoy.json
            subPath: convoy.json
          ports:
            - name: http-server
              containerPort: 5005
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-server
          readinessProbe:
            httpGet:
              path: /health
              port: http-server
          resources:
            requests:
            {{- toYaml .Values.resources.server.requests | nindent 14 }}
            limits:
            {{- toYaml .Values.resources.server.limits | nindent 14 }}
          env:
            {{- include "convoy.deploymentPodEnvironments" . | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
