apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mautic.fullname" . }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mautic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mautic
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
      labels:
        {{- include "mautic.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mautic
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mautic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 90
          volumeMounts:
            - mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
              name: php-ini
            - mountPath: /var/www/html
              name: mautic-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- include "mautic.deploymentPodEnvironments" . | nindent 12 }}
        {{- if and .Values.persistence.enabled .Values.persistence.filebrowser.enabled }}
        - name: filebrowser
          image: filebrowser/filebrowser
          ports:
            - name: filebrowser
              containerPort: 8000
          volumeMounts:
            - name: mautic-data
              mountPath: /srv
          resources:
            requests:
              cpu: 1m
              memory: 10Mi
          env:
            - name: FB_BASEURL
              value: {{ .Values.persistence.filebrowser.baseUrl }}
            - name: FB_PORT
              value: "8000"
            - name: FB_USERNAME
              value: {{ .Values.persistence.filebrowser.username }}
            - name: FB_PASSWORD
              value: {{ include "mautic.filebrowser.password" . }}
        {{- end }}
      volumes:
        - name: mautic-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "common.names.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: php-ini
          configMap:
            name: {{ include "mautic.fullname" . }}
            items:
              - key: php.ini
                path: php.ini
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
