annotations:
  category: Work Flow
  licenses: Apache-2.0

apiVersion: v2
name: n8n
version: 0.218.0-20230310
appVersion: 0.218.0
type: application

description: "A Kubernetes Helm chart for n8n a free and open fair-code licensed node based Workflow Automation Tool. Easily automate tasks across different services."
home: https://github.com/NurFaizin/helm-charts/n8n
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
  - Workflow Automation
  - Workflow
  - iPaaS
  - integration-framework
  - low-code-plattform
  - low-code
sources:
  - https://github.com/n8n-io/n8n
  - https://n8n.io/
maintainers:
  - name: Nur Faizin

dependencies:
  - name: redis
    version: 17.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mariadb
    version: 11.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
