apiVersion: v1
kind: Service
metadata:
  name: {{ include "beanstalkd.fullname" . }}
  labels:
    {{- include "beanstalkd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: beanstalkd
      protocol: TCP
      name: beanstalkd
  selector:
    {{- include "beanstalkd.selectorLabels" . | nindent 4 }}
